"use client";
import {useEffect,useRef} from "react";
import * as THREE from "three";
import outline from "./aa-shape.json";
import {RoomEnvironment} from "three/addons/environments/RoomEnvironment.js";
import {motionState,poseAt,clamp,range} from "./motion";
type Face={points:THREE.Vector3[];holes?:THREE.Vector3[][];normal:THREE.Vector3;center:THREE.Vector3};
export default function Sculpture(){const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=root.current!,scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,200);camera.position.z=9;camera.updateMatrixWorld();
 const group=new THREE.Group();group.rotation.order="ZYX";scene.add(group);const material=new THREE.MeshPhysicalMaterial({color:0xe2e5ff,metalness:.97,roughness:.095,clearcoat:1,clearcoatRoughness:.03,iridescence:.5,iridescenceIOR:1.4,iridescenceThicknessRange:[180,550],envMapIntensity:2.25});
 const geometries:THREE.ExtrudeGeometry[]=[],faces:Face[]=[];
 for(const polygon of outline){const shape=new THREE.Shape();polygon[0].forEach(([x,y],i)=>i?shape.lineTo((x-182)/60,(154-y)/60):shape.moveTo((x-182)/60,(154-y)/60));shape.closePath();for(const ring of polygon.slice(1)){const hole=new THREE.Path();ring.forEach(([x,y],i)=>i?hole.lineTo((x-182)/60,(154-y)/60):hole.moveTo((x-182)/60,(154-y)/60));hole.closePath();shape.holes.push(hole);}const geo=new THREE.ExtrudeGeometry(shape,{depth:.7,bevelEnabled:true,bevelSegments:3,bevelSize:.048,bevelThickness:.045,steps:1});geo.translate(0,0,-.35);geometries.push(geo);group.add(new THREE.Mesh(geo,material));
 const rings=polygon.map(ring=>ring.slice(0,-1).map(([x,y])=>new THREE.Vector3((x-182)/60,(154-y)/60,0)));
 for(const side of [-1,1]){const points=rings[0].map(v=>v.clone().setZ(side*.395)),holes=rings.slice(1).map(r=>r.map(v=>v.clone().setZ(side*.395)));faces.push({points,holes,normal:new THREE.Vector3(0,0,side),center:new THREE.Vector3(0,0,side*.395)});}
 for(const ring of rings){for(let j=0;j<ring.length;j++){const a=ring[j],b=ring[(j+1)%ring.length];const normal=new THREE.Vector3(b.y-a.y,a.x-b.x,0).normalize().negate();const points=[a.clone().setZ(.395),b.clone().setZ(.395),b.clone().setZ(-.395),a.clone().setZ(-.395)];faces.push({points,normal,center:a.clone().add(b).multiplyScalar(.5)});}}}
 let webgl:THREE.WebGLRenderer|undefined,pmrem:THREE.PMREMGenerator|undefined,environment:THREE.WebGLRenderTarget|undefined,environmentScene:RoomEnvironment|undefined,context:CanvasRenderingContext2D|null=null;const canvas=document.createElement("canvas");
 try{webgl=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:"high-performance"});webgl.setClearColor(0,0);webgl.setPixelRatio(Math.min(devicePixelRatio,1.5));webgl.toneMapping=THREE.ACESFilmicToneMapping;webgl.toneMappingExposure=1.08;environmentScene=new RoomEnvironment();for(const[x,y,z,color]of[[-3,1,2,0x862bff],[3,-1,2,0x24e6e2],[0,4,-3,0xff916a]] as number[][]){const light=new THREE.Mesh(new THREE.PlaneGeometry(2,7),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide}));light.position.set(x,y,z);light.lookAt(0,0,0);environmentScene.add(light);}pmrem=new THREE.PMREMGenerator(webgl);environment=pmrem.fromScene(environmentScene,.02);scene.environment=environment.texture;scene.add(new THREE.HemisphereLight(0xead8ff,0x442088,.9));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(3,4,6);scene.add(light);element.dataset.renderer="webgl";}catch{const fallback=document.createElement("canvas");context=fallback.getContext("2d",{alpha:true});element.appendChild(fallback);element.dataset.renderer="geometry-canvas";}
 if(webgl)element.appendChild(canvas);const output=webgl?canvas:element.querySelector("canvas")!;
 let width=element.clientWidth,height=element.clientHeight,ratio=1,frame=0,paintRevision=0;const resize=()=>{paintRevision++;width=element.clientWidth;height=element.clientHeight;ratio=webgl?Math.min(devicePixelRatio,1.5):1;camera.aspect=width/height;camera.updateProjectionMatrix();if(webgl)webgl.setSize(width,height);else{output.width=width*ratio;output.height=height*ratio;output.style.width=`${width}px`;output.style.height=`${height}px`;}};resize();window.addEventListener("resize",resize);
 const halos=new THREE.Group();scene.add(halos);const haloMaterials:THREE.LineBasicMaterial[]=[],haloGeometry:THREE.BufferGeometry[]=[];
 const haloPaths=[0,1,2].map((j)=>Array.from({length:65},(_,i)=>{const angle=i/64*Math.PI*2,r=2.85+j*.25;return new THREE.Vector3(Math.cos(angle)*r,Math.sin(angle)*r,0);}));
 const haloColors=[0x9759ff,0x45e5ec,0xff955b];const haloLines=haloPaths.map((points,i)=>{const geometry=new THREE.BufferGeometry().setFromPoints(points),mat=new THREE.LineBasicMaterial({color:haloColors[i],transparent:true,opacity:.45,depthWrite:false});const line=new THREE.Line(geometry,mat);line.rotation.set(.9+i*.32,.25+i*.95,i*.7);halos.add(line);haloMaterials.push(mat);haloGeometry.push(geometry);return line;});
 const haloProject=new THREE.Vector3();
 const renderHalos=(alpha:number)=>{if(!context||alpha<.01)return;const ctx=context;ctx.save();ctx.globalAlpha=alpha;ctx.lineWidth=1.2;haloLines.forEach((line,i)=>{ctx.beginPath();haloPaths[i].forEach((v,j)=>{haloProject.copy(v).applyMatrix4(line.matrixWorld).project(camera);const x=(haloProject.x*.5+.5)*width,y=(-haloProject.y*.5+.5)*height;if(j===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});const gradient=ctx.createLinearGradient(width*.2,height*.15,width*.8,height*.85);gradient.addColorStop(0,["#bf6dff","#55ddec","#ffca82"][i]);gradient.addColorStop(.5,"#6550c011");gradient.addColorStop(1,["#6dfaff","#ac62ff","#ff649d"][i]);ctx.strokeStyle=gradient;ctx.stroke();});ctx.restore();};
 const white=new THREE.Color(1,1,1),normalMatrix=new THREE.Matrix3(),color=new THREE.Color(),projected=new THREE.Vector3(),normal=new THREE.Vector3(),center=new THREE.Vector3();let px=0,py=0,phase=0,lastTime=0,fpsStart=0,fpsFrames=0,lastPaintS=-1,lastPaintMaterial="",lastPaintRevision=-1;
 const reflection=(x:number,y:number,nx:number,ny:number,nz:number,rainbow:number,t:number)=>{const u=x*.22+nx*1.3+Math.sin(t*.23)*.15,v=y*.35+ny*.6;const stripe=Math.sin(u*8+v*4+nz*2),soft=Math.sin(u*3.3-v*2.8),shine=Math.pow(Math.max(0,Math.cos(u*7-v*3)),20);let l=.035+.7*Math.pow(stripe*.5+.5,3)+.12*(soft*.5+.5)+shine*.85;l=clamp(l,.025,1);const hue=(.6+u*.15+v*.2+t*.008)%1;if(rainbow<.23){color.setRGB(l*.91,l*.94,l);}else{color.setHSL((hue+1)%1,.15+rainbow*.7,l*.8);}color.lerp(white,clamp(shine*.8));color.convertLinearToSRGB();return `rgb(${Math.floor(color.r*255)},${Math.floor(color.g*255)},${Math.floor(color.b*255)})`;};
 const renderCPU=(rainbow:number,time:number,wire:number,haloAlpha:number)=>{const ctx=context!;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);renderHalos(haloAlpha);normalMatrix.getNormalMatrix(group.matrixWorld);const out:{rings:number[][][];depth:number;normal:THREE.Vector3;center:THREE.Vector3}[]=[];
 for(const f of faces){const c=f.center.clone().applyMatrix4(group.matrixWorld),n=f.normal.clone().applyMatrix3(normalMatrix).normalize();if(n.dot(camera.position.clone().sub(c))<=0)continue;const rings:number[][][]=[];let skip=false;for(const ring of [f.points,...(f.holes||[])]){const p:number[][]=[];for(const vertex of ring){projected.copy(vertex).applyMatrix4(group.matrixWorld);if(projected.z>8.6){skip=true;break;}projected.project(camera);p.push([(projected.x*.5+.5)*width,(-projected.y*.5+.5)*height]);}rings.push(p);}if(!skip)out.push({rings,depth:c.z,normal:n,center:c});}out.sort((a,b)=>a.depth-b.depth);
 for(const face of out){const p=face.rings[0],n=face.normal,c=face.center;ctx.beginPath();for(const ring of face.rings){ctx.moveTo(ring[0][0],ring[0][1]);for(let i=1;i<ring.length;i++)ctx.lineTo(ring[i][0],ring[i][1]);ctx.closePath();}const minX=Math.min(...p.map(q=>q[0])),maxX=Math.max(...p.map(q=>q[0])),minY=Math.min(...p.map(q=>q[1])),maxY=Math.max(...p.map(q=>q[1]));const gradient=ctx.createLinearGradient(minX,minY,Math.max(minX+1,maxX),Math.max(minY+1,maxY));const broad=face.rings.length>1;for(let i=0;i<=8;i++){const q=i/8,span=broad?4:1.2;gradient.addColorStop(q,reflection(c.x+(q-.5)*span,c.y-(q-.5)*span*.7,n.x,n.y,n.z,rainbow,time));}ctx.fillStyle=gradient;ctx.globalAlpha=1-wire*.35;ctx.fill("evenodd");ctx.lineWidth=wire>.4?.9:1;ctx.strokeStyle=wire>.4?"rgba(225,225,250,.8)":"rgba(208,220,246,.4)";ctx.stroke();}ctx.globalAlpha=1;};
 const animate=(ms:number)=>{frame=requestAnimationFrame(animate);if(document.hidden)return;const s=motionState.s,p=poseAt(s),t=ms*.001,mobile=width<=900,fit=Math.min(1,(width/height)/.95);
 element.style.opacity=String(p.opacity);element.style.visibility=p.opacity>.001?"visible":"hidden";
 if(p.opacity<.002)return;
 // On software-rendered devices, leave a still 3D frame behind idle video panels.
 // Scrolling and pointer changes still redraw the actual perspective geometry.
 if(context&&s>.8&&paintRevision===lastPaintRevision&&Math.abs(s-lastPaintS)<.00001&&motionState.material===lastPaintMaterial&&Math.abs(motionState.pointerX-px)<.001&&Math.abs(motionState.pointerY-py)<.001)return;
 lastPaintS=s;lastPaintRevision=paintRevision;lastPaintMaterial=motionState.material;
 px+=(motionState.pointerX-px)*.05;py+=(motionState.pointerY-py)*.05;
 fpsFrames++;if(ms-fpsStart>1000){element.dataset.fps=String(Math.round(fpsFrames*1000/(ms-fpsStart)));fpsFrames=0;fpsStart=ms;}const delta=Math.min(.05,(ms-lastTime)*.001);lastTime=ms;const working=range(s,.6,1)*(1-range(s,3.3,3.7));phase+=delta*.5*working;const idle=motionState.reduced?0:(1-range(s,0,1))*.17;group.rotation.set(p.rx+Math.sin(t*.7)*idle+py*.1,p.ry+Math.sin(t*.5)*idle+px*.16+(motionState.reduced?0:phase*working),p.rz);group.position.set(mobile?p.x*.3:p.x,p.y,p.z);const pointerWeight=1-range(s,4.4,4.9)*(1-range(s,6.2,6.8));camera.position.x=px*.65*pointerWeight;camera.position.y=-py*.4*pointerWeight;camera.lookAt(0,0,0);camera.updateMatrixWorld();group.scale.setScalar(p.scale*fit);const edge=range(s,4.4,4.9)*(1-range(s,5.8,6.2));group.scale.z*=1-edge*.86;group.updateMatrixWorld(true);const haloAlpha=(1-range(s,3.5,4))*p.opacity;halos.visible=haloAlpha>.01;halos.position.set(0,0,-1.15);halos.rotation.set(.05+py*.15,t*(motionState.reduced?0:.06),Math.sin(t*.16)*.2);halos.scale.setScalar(fit);haloMaterials.forEach(m=>m.opacity=haloAlpha*.48);halos.updateMatrixWorld(true);
 element.style.opacity=String(p.opacity);element.style.visibility=p.opacity>.001?"visible":"hidden";element.dataset.timeline=s.toFixed(3);element.dataset.rotation=group.rotation.y.toFixed(3);element.dataset.scale=group.scale.x.toFixed(3);
 if(p.opacity<.002)return;const rainbow=motionState.material==="iridescent"?1:p.rainbow;material.iridescence=rainbow;material.roughness=.075+rainbow*.02;material.wireframe=p.wire>.65;
 if(webgl)webgl.render(scene,camera);else if(context)renderCPU(rainbow,t,p.wire,haloAlpha*.65);
 };frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);geometries.forEach(g=>g.dispose());haloGeometry.forEach(g=>g.dispose());haloMaterials.forEach(m=>m.dispose());material.dispose();environment?.dispose();environmentScene?.dispose();pmrem?.dispose();webgl?.dispose();element.replaceChildren();};
 },[]);
 return <div className="sculpture" ref={root} aria-hidden="true"/>;
}
